### ISSUE TITLE
Breaking changes on minor version releases

### ISSUE THREAD

**Issue by dbp** [michaelschade/hs-stripe#38]
0.8.3, on hackage, changed the type of Card to have 8 fields instead of 7. This will break any code that uses Card! It would be really nice if this package followed PVP, so that breaking changes brought major releases (so instead of 0.8.3, it would have been 0.9.0).

**Comment by LukeHoersten** [comment]
That was an oversight on my part. I'll accept a patch or get to making the change eventually

**Comment by dbp** [comment]
There isn't really anything that can be done (such is the nature of hackage)... But I'm glad to know that it wasn't intentional (it's hard to tell these days, with all the back and forth about versioning). I'll close this now - just wanted to bring it up.

**Comment by LukeHoersten** [comment]
We strictly follow the PVP. We can mark the current version as deprecated. I just need to get the time to do it.
